import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"], weight:["400","500","600","700"]
});
const Ovo1 = Ovo({
  subsets: ["latin"], weight:["400"]
});

export const metadata = {
  title:"Portfolio/Joyanta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`
          ${outfit.className} ${Ovo1.className}
          antialiased leading-8 overflow-x-hidden
          bg-black bg-gradient-to-br from-black via-[#11001F] to-gray-900
          text-gray-100 transition-colors duration-500
        `}
        style={{
          minHeight: "100vh",
        }}
      >
        {children}
      </body>
    </html>
  );
}
